### ISSUE TITLE
README does not contain Examples 

### ISSUE THREAD

**Issue by KathyReid** [TREE-Ind/bedtime-stories-skill#2]
Hi Joshua, 
Sorry I should have checked for this on the acceptance check - there is no Examples section in your README so in https://market.mycroft.ai in the speech bubble there are no phrases; 
![screenshot from 2019-01-05 01-28-28](https://user-images.githubusercontent.com/114158/50693298-a9b12180-108a-11e9-9f71-36605c98927b.png)

**Comment by luke5sky** [comment]
PR #4 should fix this

**Comment by TREE-Ind** [comment]
The PR to add example intents has been merged.  Thanks @luke5sky and @KathyReid :)  Closing this issue
